### ISSUE TITLE
Update remark and related packages to remark v13+

### ISSUE THREAD

**Issue by malsf21** [stylelint/remark-preset#4]
In https://github.com/stylelint/postcss-css-in-js/pull/70 we discussed updating `remark` and its related dependencies (e.g. `remark-cli`) to their latest versions. I think we'll have to do this manually, just to make sure there are no breaking changes (the new version of remark has quite a few).

Packages to explicitly check:

* `remark-frontmatter`
* `remark-preset-lint-recommended`
* `remark-preset-prettier`
* `remark-validate-links`
* `remark-cli`

I'll take a look at this and aim to get it done by the weekend.

**Comment by jeddy3** [comment]
> I think we'll have to do this manually,

Yep. I suspect the packages will be compatible as they are all official.

> I'll take a look at this and aim to get it done by the weekend.

Awesomesauce.
