### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/remark-preset#7]
We will ship the next major version **3.0.0** including the following breaking changes within PR #6:

- Bump `remark` from v13 to v14
- Support only ESM

Because `remark` supports only ESM since v14. Please check out <https://github.com/remarkjs/remark/releases/tag/14.0.0> for details.

### Checklist

- [x] Merge PR #6
- [x] Update `CHANGELOG.md`
- [x] Merge PR #9
- [x] Run the `npm run release` command

/cc @jeddy3

**Comment by jeddy3** [comment]
LGTM. Feel free to merge the PR, and then update the changelog. Probably create a pull request for the outdated dependencies.

**Comment by ybiquitous** [comment]
Yes. I've merged the PR and updated the changelog.
Next, I'm preparing for a PR to update outdated deps. 👍🏼

**Comment by ybiquitous** [comment]
Preparation is now complete. I'm going to start the release process. 💪🏼

**Comment by ybiquitous** [comment]
Released! 🎉 

- https://github.com/stylelint/remark-preset/releases/tag/3.0.0
- https://www.npmjs.com/package/@stylelint/remark-preset/v/3.0.0

@jeddy3 Thank you so much for the help!

**Comment by jeddy3** [comment]
> @jeddy3 Thank you so much for the help!

No worries. Thanks for doing the legwork and keeping us up to date!
